language: python
python:
    - 2.7
install:
    - "pip install coverage"
    - "pip install coveralls"
    - "pip install -r requirements.txt"
script:
    - "coverage run --source=rblg tests.py"
after_success:
    coveralls
